export enum RoleEnum {
    ADMIN = 'NBP04.ADMIN',
    CLAIMS_ADJUSTER = 'NBP04.CLAIMS_ADJUSTER',
    FIELD_TECHNICIAN = 'NBP04.FIELD_TECHNICIAN',
    STATION_MANAGER = 'NBP04.STATION_MANAGER',
    DRIVER = 'NBP04.DRIVER'
} 