-- DO NOT EXECUTE

-- CREATE OR REPLACE VIEW NBP04.VW_WEEKLY_AVG_FUEL_PRICE AS
-- SELECT
--     c.ID AS COMPANY_ID,
--     c.NAME AS COMPANY_NAME,
--     f.ID AS FUEL_ID,
--     f.NAME AS FUEL_NAME,
--     -- Extract ISO year and week from ISSUE_DATE
--     TO_CHAR(fp.ISSUE_DATE, 'IYYY') AS YEAR,
--     TO_CHAR(fp.ISSUE_DATE, 'WW') AS WEEK,
--     -- Get start and end dates of the week
--     TRUNC(fp.ISSUE_DATE, 'WW') AS WEEK_START_DATE,
--     TRUNC(fp.ISSUE_DATE, 'WW') + 6 AS WEEK_END_DATE,
--     ROUND(AVG(fp.PRICE), 2) AS AVG_PRICE
-- FROM
--     NBP04.FUEL_PRICE fp
--         INNER JOIN NBP04.COMPANY c
--                    ON fp.GAS_STATION_ID = c.ID
--         INNER JOIN NBP04.FUEL f
--                    ON fp.FUEL_ID = f.ID
-- GROUP BY
--     c.ID, c.NAME,
--     f.ID, f.NAME,
--     TO_CHAR(fp.ISSUE_DATE, 'IYYY'),
--     TO_CHAR(fp.ISSUE_DATE, 'WW'),
--     TRUNC(fp.ISSUE_DATE, 'WW');