BEGIN
    DECLARE SCRIPT_ID RAW(16) := '33880B3146647FE5E063143410AC812D';
    BEGIN
        DECLARE NOW DATE;
        BEGIN
            DECLARE EXEC_COUNT INT := 0;
            BEGIN
                SELECT COUNT(1) INTO EXEC_COUNT FROM SCRIPT_EXECUTION_HISTORY WHERE ID = SCRIPT_ID;
                IF EXEC_COUNT = 0 THEN

                    INSERT INTO FUEL_PRICE (PRICE, ISSUE_DATE, FUEL_ID, GAS_STATION_ID)
                    VALUES (1.25, TO_DATE('2025-04-24', 'YYYY-MM-DD'), (SELECT ID FROM FUEL WHERE NAME = 'Petrol'), (SELECT ID FROM COMPANY WHERE NAME = 'FuelExpress Station' AND COMPANY_TYPE = 3));

                    INSERT INTO FUEL_PRICE (PRICE, ISSUE_DATE, FUEL_ID, GAS_STATION_ID)
                    VALUES (1.35, TO_DATE('2025-04-24', 'YYYY-MM-DD'), (SELECT ID FROM FUEL WHERE NAME = 'Diesel'), (SELECT ID FROM COMPANY WHERE NAME = 'GoGas Plus' AND COMPANY_TYPE = 3));

                    INSERT INTO FUEL_PRICE (PRICE, ISSUE_DATE, FUEL_ID, GAS_STATION_ID)
                    VALUES (1.05, TO_DATE('2025-04-24', 'YYYY-MM-DD'), (SELECT ID FROM FUEL WHERE NAME = 'LPG'), (SELECT ID FROM COMPANY WHERE NAME = 'Highway Fuel Hub' AND COMPANY_TYPE = 3));

                    INSERT INTO FUEL_PRICE (PRICE, ISSUE_DATE, FUEL_ID, GAS_STATION_ID)
                    VALUES (1.50, TO_DATE('2025-04-24', 'YYYY-MM-DD'), (SELECT ID FROM FUEL WHERE NAME = 'CNG'), (SELECT ID FROM COMPANY WHERE NAME = 'FuelExpress Station' AND COMPANY_TYPE = 3));

                    INSERT INTO FUEL_PRICE (PRICE, ISSUE_DATE, FUEL_ID, GAS_STATION_ID)
                    VALUES (0.80, TO_DATE('2025-04-24', 'YYYY-MM-DD'), (SELECT ID FROM FUEL WHERE NAME = 'Electric'), (SELECT ID FROM COMPANY WHERE NAME = 'GoGas Plus' AND COMPANY_TYPE = 3));

                    COMMIT;

                    SELECT CAST(SYSTIMESTAMP AT TIME ZONE 'UTC' AS DATE) INTO NOW FROM DUAL;

                    INSERT INTO SCRIPT_EXECUTION_HISTORY
                    VALUES (SCRIPT_ID, 'fuel-price-seed.sql', NOW);
                    COMMIT;
                END IF;
            END;
        END;
    END;
END;
