BEGIN
    DECLARE SCRIPT_ID RAW(16) := '34DEB1D4CFBB7390E063143410AC5D2F';
    BEGIN
        DECLARE NOW DATE;
        BEGIN
            DECLARE EXEC_COUNT INT := 0;
            BEGIN
                SELECT COUNT(1) INTO EXEC_COUNT FROM SCRIPT_EXECUTION_HISTORY WHERE ID = SCRIPT_ID;
                IF EXEC_COUNT = 0 THEN

                    DECLARE
                        V_ID1 NUMBER; V_ID2 NUMBER; V_ID3 NUMBER;
                        V_ID4 NUMBER; V_ID5 NUMBER; V_ID6 NUMBER;
                        V_ID7 NUMBER; V_ID8 NUMBER; V_ID9 NUMBER;
                        V_ID10 NUMBER; V_ID11 NUMBER; V_ID12 NUMBER;
                        V_ID13 NUMBER; V_ID14 NUMBER; V_ID15 NUMBER;
                        V_ID16 NUMBER; V_ID17 NUMBER; V_ID18 NUMBER;
                        V_ID19 NUMBER; V_ID20 NUMBER;

                        D_ID1 NUMBER; D_ID2 NUMBER; D_ID3 NUMBER;
                        D_ID4 NUMBER; D_ID5 NUMBER; D_ID6 NUMBER;
                        D_ID7 NUMBER; D_ID8 NUMBER; D_ID9 NUMBER;
                        D_ID10 NUMBER; D_ID11 NUMBER; D_ID12 NUMBER;
                    BEGIN
                        SELECT ID INTO V_ID1 FROM VEHICLE WHERE LICENSE_PLATE = 'BG123AA';
                        SELECT ID INTO V_ID2 FROM VEHICLE WHERE LICENSE_PLATE = 'BG789TT';
                        SELECT ID INTO V_ID3 FROM VEHICLE WHERE LICENSE_PLATE = 'BG456MM';
                        SELECT ID INTO V_ID4 FROM VEHICLE WHERE LICENSE_PLATE = 'BG111BB';
                        SELECT ID INTO V_ID5 FROM VEHICLE WHERE LICENSE_PLATE = 'BG222VV';
                        SELECT ID INTO V_ID6 FROM VEHICLE WHERE LICENSE_PLATE = 'BG333SS';
                        SELECT ID INTO V_ID7 FROM VEHICLE WHERE LICENSE_PLATE = 'BG444PP';
                        SELECT ID INTO V_ID8 FROM VEHICLE WHERE LICENSE_PLATE = 'BG555TT';
                        SELECT ID INTO V_ID9 FROM VEHICLE WHERE LICENSE_PLATE = 'BG666SS';
                        SELECT ID INTO V_ID10 FROM VEHICLE WHERE LICENSE_PLATE = 'BG777BB';
                        SELECT ID INTO V_ID11 FROM VEHICLE WHERE LICENSE_PLATE = 'BG888HH';
                        SELECT ID INTO V_ID12 FROM VEHICLE WHERE LICENSE_PLATE = 'BG999CC';
                        SELECT ID INTO V_ID13 FROM VEHICLE WHERE LICENSE_PLATE = 'BG101CV';
                        SELECT ID INTO V_ID14 FROM VEHICLE WHERE LICENSE_PLATE = 'BG202WG';
                        SELECT ID INTO V_ID15 FROM VEHICLE WHERE LICENSE_PLATE = 'BG303MV';
                        SELECT ID INTO V_ID16 FROM VEHICLE WHERE LICENSE_PLATE = 'BG404JP';
                        SELECT ID INTO V_ID17 FROM VEHICLE WHERE LICENSE_PLATE = 'BG505LM';
                        SELECT ID INTO V_ID18 FROM VEHICLE WHERE LICENSE_PLATE = 'BG606CM';
                        SELECT ID INTO V_ID19 FROM VEHICLE WHERE LICENSE_PLATE = 'BG707RD';
                        SELECT ID INTO V_ID20 FROM VEHICLE WHERE LICENSE_PLATE = 'BG909HY';

                        SELECT D.ID INTO D_ID1 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'anezovic';
                        SELECT D.ID INTO D_ID2 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'nmaric';
                        SELECT D.ID INTO D_ID3 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'lkovac';
                        SELECT D.ID INTO D_ID4 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'mpetrovic';
                        SELECT D.ID INTO D_ID5 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'nbegovic';
                        SELECT D.ID INTO D_ID6 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'msoftic';
                        SELECT D.ID INTO D_ID7 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'ikaracic';
                        SELECT D.ID INTO D_ID8 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'jsmith';
                        SELECT D.ID INTO D_ID9 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'mbrown';
                        SELECT D.ID INTO D_ID10 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'ejohnson';
                        SELECT D.ID INTO D_ID11 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'dwilson';
                        SELECT D.ID INTO D_ID12 FROM DRIVER D JOIN nbp.nbp_user U ON D.USER_ID = U.ID WHERE U.USERNAME = 'lmiller';

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-01', DATE '2025-05-01', 'Prekoračenje brzine', 1, 'Sarajevo', 1, 150.0, V_ID1, D_ID1);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-05', DATE '2025-05-05', 'Nepoštivanje saobraćajnih propisa', 5, 'Mostar', 1, 100.0, V_ID2, D_ID2);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-10', DATE '2025-05-10', 'Nepropisno parkiranje', 3, 'Zenica', 2, 75.0, V_ID3, D_ID3);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-12', DATE '2025-05-12', 'Nema pojasa', 4, 'Tuzla', 1, 50.0, V_ID4, D_ID4);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-15', DATE '2025-05-15', 'Nepoštivanje saobraćajnih propisa', 5, 'Sarajevo', 2, 200.0, V_ID5, D_ID5);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-18', DATE '2025-05-18', 'Vožnja kroz crveno svjetlo', 2, 'Banja Luka', 1, 180.0, V_ID6, D_ID6);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-20', DATE '2025-05-20', 'Nedostatak dokumenata', 5, 'Bihać', 1, 120.0, V_ID7, D_ID7);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-22', DATE '2025-05-22', 'Nepoštivanje znaka stop', 6, 'Travnik', 2, 90.0, V_ID8, D_ID8);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-25', DATE '2025-07-25', 'Nepropisno parkiranje', 3, 'Goražde', 1, 70.0, V_ID9, D_ID9);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-04-28', DATE '2025-07-28', 'Prekoračenje brzine u naselju', 1, 'Široki Brijeg', 2, 160.0, V_ID10, D_ID10);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-01', DATE '2025-06-01', 'Vožnja bez važeće registracije', 5, 'Foča', 1, 130.0, V_ID11, D_ID11);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-03', DATE '2025-06-03', 'Prekoračenje brzine u zoni škole', 1, 'Gradačac', 2, 200.0, V_ID12, D_ID12);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-05', DATE '2025-06-05', 'Nepropisno zaustavljanje', 6, 'Čapljina', 1, 60.0, V_ID13, D_ID1);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-07', DATE '2025-06-07', 'Vožnja bez pojasa', 4, 'Sanski Most', 2, 50.0, V_ID14, D_ID2);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-10', DATE '2025-06-10', 'Parkiranje na pješačkom prijelazu', 3, 'Livno', 1, 90.0, V_ID15, D_ID3);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-12', DATE '2025-06-12', 'Vožnja kroz crveno svjetlo', 2, 'Banja Luka', 1, 180.0, V_ID16, D_ID4);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-14', DATE '2025-06-14', 'Nedostatak ličnih dokumenata', 5, 'Doboj', 2, 120.0, V_ID17, D_ID5);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-16', DATE '2025-06-16', 'Nepropisno skretanje', 6, 'Travnik', 1, 70.0, V_ID18, D_ID6);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-18', DATE '2025-06-18', 'Parkiranje na mjestu za invalide', 3, 'Bihać', 2, 100.0, V_ID19, D_ID7);

                        INSERT INTO TRAFFIC_FINE (ISSUE_DATE, PAYMENT_DUE_DATE, VIOLATION_DESCRIPTION, VIOLATION_TYPE, LOCATION, PAYMENT_STATUS, AMOUNT, VEHICLE_ID, DRIVER_ID)
                        VALUES (DATE '2025-05-20', DATE '2025-06-20', 'Vožnja bez pojasa', 4, 'Goražde', 1, 50.0, V_ID20, D_ID8);
                    END;

                    COMMIT;

                    SELECT CAST(SYSTIMESTAMP AT TIME ZONE 'UTC' AS DATE) INTO NOW FROM DUAL;

                    INSERT INTO SCRIPT_EXECUTION_HISTORY
                    VALUES (SCRIPT_ID, 'traffic-fine-seed.sql', NOW);

                    COMMIT;
                END IF;
            END;
        END;
    END;
END;
