export enum RoleEnum {
  ADMIN = 'NBP04.ADMIN',
  DRIVER = 'NBP04.DRIVER',
  STATION_MANAGER = 'NBP04.STATION_MANAGER',
  FIELD_TECHNICIAN = 'NBP04.FIELD_TECHNICIAN',
  CLAIMS_ADJUSTER = 'NBP04.CLAIMS_ADJUSTER'
}
